
spring:
  application:
    name: capturedin-auth

  data:
    mongodb:
      database: capturedin_auth

server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  basic:
    enable: false